language: d
before_install:
  # No SDL2 in the default repos yet
  - sudo apt-add-repository ppa:zoogie/sdl2-snapshots -y
  # GCC 4.8 not in the repos either
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get -qq install cmake build-essential libsdl2-dev libsdl2-ttf-dev bison flex libpng-dev
  