language: d
sudo: false

addons:
  apt:
    packages:
      - libsdl2-dev

matrix:
  allow_failures:
    - d: ldc-0.16.1
  include:
    - d: ldc-0.16.1
    - d: dmd-2.069.0-rc2
    - d: dmd-2.068.2
    - d: dmd-2.068.1
    - d: dmd-2.068.0
